name: Build iOS App MANU

on:
  pull_request:
    branches: [ develop ]

jobs:
  build-simulator:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          xcode-version: '16.3'

      - name: Install dependencies (SPM)
        run: |
          xcodebuild \
            -resolvePackageDependencies \
            -project manu.xcodeproj \
            -scheme manu

      - name: Build for iOS Simulator without signing
        run: |
          xcodebuild clean build \
            -project manu.xcodeproj \
            -scheme manu \
            -destination "platform=iOS Simulator,name=iPhone 14" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""
